### ISSUE TITLE
need global too

### ISSUE THREAD

**Issue by jbenet** [whyrusleeping/gx#11]
i'd like to be able to setup my imports like:

```
ipfs/<hash>/pkgname
gx/<hash>/pkgname
```
so that there's one global location for stuff. and symlink to that.

(of course, we do need to handle the case where things are vendored locally too. but the global case is really nice to have)

**Comment by noffle** [comment]
I'd like to see us support this like [npm does](https://docs.npmjs.com/files/folders#prefix-configuration) (an env var specifying where your global path is, but defaulting to local vendoring).

**Comment by whyrusleeping** [comment]
I want this to be a 'known location' based on the language. There is a global flag right now, and for go it installs packages into `$GOPATH/src`. For other languages, we will want to do the *right* thing for each language
