### ISSUE TITLE
gx install <pkg> -- does nothing

### ISSUE THREAD

**Issue by jbenet** [whyrusleeping/gx#12]
```
> gx install QmXrnpeF2R5k8StJXCPQjbAYYrjF23qAxpgyfnSGge43Z5
> git status
> ls vendor/src
>
```
no change. nothing downloaded, and package.json not changed. and no error.

**Comment by jbenet** [comment]
looks like `gx import <pkg>` is the thing gx wants me to do.

- other pkg mgrs use `gx install <pkg>` (see npm)
- at the very least `gx install <pkg>` should return an error.

**Comment by whyrusleeping** [comment]
@jbenet right. I had the concepts of 'fetch all dependencies' and 'grab a new dependency' as separate in my mind. Do you think that it should *just* be install?

Where `gx install` has the same behaviour that it currently has, and `gx install XYZ` does what `gx import XYZ` does now?

**Comment by noffle** [comment]
(Aside: `gx` is super cool!)

I'm partial to the way npm separates downloading ("installing") a package and adding a package dependency ("saving"):

`npm install X`: download X and place it in vendor/ -- don't update package.json
`npm install --save X`: like the above, but add it as a package dependency
`npm install`: expands to `npm install X Y Z`, assuming pkg depends on X, Y, and Z

**Comment by whyrusleeping** [comment]
@noffle yeah, i think i agree with this. 

how about this:
`gx install X` acts like `npm install X`, no package.json changes
`gx import X` acts like `npm install --save X`, and updates the package.json
`gx install --save X` can essentially be an alias to `gx import`
`gx install` currently expands to `gx install X Y Z`, just like `npm install`

**Comment by noffle** [comment]
@whyrusleeping yes! Brilliant. :)

**Comment by whyrusleeping** [comment]
@noffle yeah, i want to keep that. Right now, the link is added at the same time its imported, and the linkname is written to the package.json so that the same link is created on further installs.

**Comment by whyrusleeping** [comment]
this now does a thing, closing
