### ISSUE TITLE
`gx install` on the first time creates a vendor directory, but subsequently only installs into GOPATH

### ISSUE THREAD

**Issue by CMCDragonkai** [whyrusleeping/gx#124]
When first tried gx, I used:

```
gx get QmdzDdLZ7nj133QvNHypyS9Y39g35bMFk5DJ2pmX7YqtKU
```

Which gave me a directory `QmdzDdLZ7nj133QvNHypyS9Y39g35bMFk5DJ2pmX7YqtKU`.

Inside I could run `gx install`. Which on the first time created a vendor directory.

I have since deleted this directory.

The next time I tried this, it always installed into my `GOPATH` directory. Why is this? I noticed that there was a `GOPATH/src/gx` folder, and I deleted it, but it still installs globally instead of locally.

The README.md indicates that `gx install` by default should always install into a local vendor folder.

**Comment by whyrusleeping** [comment]
@CMCDragonkai apologies, The readme needs to be updated. Installs are now global by default.

**Comment by whyrusleeping** [comment]
I have updated the readme. Closing this issue now, if you still have questions please reopen this issue,or open a new one
