### ISSUE TITLE
gx's pkgfile should avoid collision with npm's package.json

### ISSUE THREAD

**Issue by rht** [whyrusleeping/gx#13]
In particular dependencies, devDependencies, peerDependencies.

(though why would 2 package managers share a package.json?)

**Comment by jbenet** [comment]
@rht to leverage the existence of npm tooling + standard practices. may want to use `gxDependencies` or something. it's standard practice in npm to have other tools define their own keywords

**Comment by noffle** [comment]
+1. I think `dependencies` and `devDependencies` are the only two `gx` might step on by default.

**Comment by whyrusleeping** [comment]
changed this, its now `gxDependencies`
