### ISSUE TITLE
Would be useful to list version or short version of the hash when installing

### ISSUE THREAD

**Issue by daviddias** [whyrusleeping/gx#131]
To distinguish duplicates

```
...
installation of dep failstore complete!
installation of dep retry-datastore complete!
installation of dep failstore complete!
...
```

**Comment by whyrusleeping** [comment]
@diasdavid There is a verbose mode you can use: `gx --verbose install`. I'm also working on a new UI for install that will have nicer information (including the hash) by default :)

**Comment by whyrusleeping** [comment]
@diasdavid try building gx from latest master, let me know what you think of the install process :)

**Comment by diasdavid** [comment]
Hit this roadblock:

```
» make install
go install
main.go:19:2: cannot find package "github.com/whyrusleeping/progmeter" in any of:
        /usr/local/go/src/github.com/whyrusleeping/progmeter (from $GOROOT)
        /Users/koruza/code/go-projects/src/github.com/whyrusleeping/progmeter (from $GOPATH)
make: *** [install] Error 1
```

Do I need to do some gx commands magic first?

Steps to reproduce:

```
> git clone git@github.com:whyrusleeping/gx.git
> cd gx
> make install
```

**Comment by VictorBjelkholm** [comment]
@diasdavid do `go get -v ./...` to install dependencies.

**Comment by diasdavid** [comment]
oh right. My bad, forgot about go workspaces.

Now I experience this:

![image](https://user-images.githubusercontent.com/1211152/27825737-7bf56faa-60a8-11e7-9c11-7807408e8e28.png)

**Comment by diasdavid** [comment]
Seems that gx is printing the 'current repo version' instead of the tool itself. This got me confused:
![image](https://user-images.githubusercontent.com/1211152/27826138-ea4ce93c-60a9-11e7-9d31-63ed54ef3cb9.png)

**Comment by diasdavid** [comment]
Using latest gx still got me this:
![image](https://user-images.githubusercontent.com/1211152/27826157-f98daf1c-60a9-11e7-8fa2-7ffd1e884fca.png)

**Comment by VictorBjelkholm** [comment]
Make sure you're actually using the right `gx` binary, when you do `gx
install --help`, it should list `--nofancy` as one of the options.

Worth to keep in mind that ipfs/go-ipfs actually pulls down its own copy of
gx when you do `make install`, so if you use that as a testing repo, make
sure to run `gx install` on it's own.

Sincerely,
Victor Bjelkholm
(+34) 672 15 90 89

**Comment by Kubuxu** [comment]
Also install location might be different so either try reopening the shell or doing `hash -r` to refresh the PATH cache.

**Comment by whyrusleeping** [comment]
> Seems that gx is printing the 'current repo version' instead of the tool itself

Huh, i guess `npm version` prints the version of the tool. gx should probably do the same here?

**Comment by diasdavid** [comment]
@whyrusleeping that is what I expected.

**Comment by VictorBjelkholm** [comment]
> Huh, i guess npm version prints the version of the tool. gx should probably do the same here?

Actually, `npm version` prints out a lot of versions, the cli version and current directories application's version included.

This is example of running `npm version` in ipfs/js-ipfs

```javascript
{ ipfs: '0.23.1',
  npm: '5.0.0',
  ares: '1.10.1-DEV',
  http_parser: '2.7.0',
  icu: '57.1',
  modules: '48',
  node: '6.9.5',
  openssl: '1.0.2k',
  uv: '1.9.1',
  v8: '5.1.281.89',
  zlib: '1.2.8' }
```
