### ISSUE TITLE
libgx

### ISSUE THREAD

**Issue by noffle** [whyrusleeping/gx#15]
I'd like to see `gx` be made into a powerful dependency resolution and retrieval **mechanism**, to be composed as a **library** within more specialized CLI (or GUI) tooling. This effectively splits policy from mechanism: `gx` is really good at retrieving package blobs from IPFS and managing dependencies, but directory structure and other policy varies by language/ecosystem.

**Comment by whyrusleeping** [comment]
we're on the same page here :)

the gx package itself is just the cli stuff, it then imports: https://github.com/whyrusleeping/gx/tree/master/gxutil

for all the actual package management logic.
I plan on having separate binaries (probably?) for language specific functionality: https://github.com/whyrusleeping/gx-go-tool

Theres still more code separation that needs to be done, but my plan is to start working on either node.js or python support for gx, and use that experience to decide how best to break out that code (and to point out to myself what needs to change per language)

**Comment by noffle** [comment]
Awesome!
