### ISSUE TITLE
viral package manager?

### ISSUE THREAD

**Issue by jvsteiner** [whyrusleeping/gx#159]
I have a project which doesn't, (and can't) use `gx` but I need to rely on a package that does.  How do I do it?  is there any possibility for this?

**Comment by jvsteiner** [comment]
sorry - figured it out

**Comment by VictorBjelkholm** [comment]
As if others come here with the same question. You can use gx for just one package, no need to have all packages downloaded via gx. Mixing good'ol `go get` and `gx install` works fine.
