### ISSUE TITLE
`gx lock-install`: option to make relative links

### ISSUE THREAD

**Issue by dgrisham** [whyrusleeping/gx#209]
I recently tried out the `feat/gx-lock` branch. The symlinks to `gx` packages created by `gx lock-install` are absolute paths. However, when Docker is building an image, it will not follow symlinks that lead outside of the build context. To fix this, the symlinks must be relative paths (since the destination paths are still inside of the package/build context).

We could have `gx lock-install` default to using relative links. However, Windows doesn't support relative paths. This leaves us with two options:

- A `--relative` option that creates relative paths instead of absolute.
- Detecting the OS and creating relative paths if not on Windows. Relative paths seem like a good default in general. However, this would mean that the default behavior varies based on platform, which may not be ideal.

**Comment by Stebalien** [comment]
We should just make them relative.

> However, Windows doesn't support relative paths. 

Windows does support relative *symlinks*, you're thinking about *junctions*. Unfortunately, symlinks require https://blogs.windows.com/buildingapps/2016/12/02/symlinks-windows-10/.

However, that's probably fine for gx-go.
