### ISSUE TITLE
when i input 'go get -u github.com/whysleeping/gx' the item return me package unrecognized import path

### ISSUE THREAD

**Issue by jujuandsn** [whyrusleeping/gx#222]
go get -u github.com/whyrusleeping/gx

package golang.org/x/crypto/ed25519: unrecognized import path "golang.org/x/crypto/ed25519" (https fetch: Get https://golang.org/x/crypto/ed25519?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
package golang.org/x/crypto/blake2s: unrecognized import path "golang.org/x/crypto/blake2s" (https fetch: Get https://golang.org/x/crypto/blake2s?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
package golang.org/x/crypto/sha3: unrecognized import path "golang.org/x/crypto/sha3" (https fetch: Get https://golang.org/x/crypto/sha3?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)

**Comment by Stebalien** [comment]
golang.org is blocked in China. You can download pre-built binaries from https://dist.ipfs.io but, unfortunately, that domain is also blocked in China. You'll have to use a proxy/VPN.

**Comment by djdv** [comment]
I am curious if these packages are mirrored on https://golang.google.cn/ and the state of access from the mainland.
