### ISSUE TITLE
Build issues for ppc64le architecture

### ISSUE THREAD

**Issue by OTLabs** [whyrusleeping/gx#235]
I would like to bring to your kind attention that it is impossible to build `gx` for `ppc64le` architecture right now due to following error:
```go build
# github.com/whyrusleeping/gx/vendor/github.com/minio/sha256-simd
vendor/github.com/minio/sha256-simd/sha256block_other.go:26:6: block redeclared in this block
	previous declaration at vendor/github.com/minio/sha256-simd/sha256block_noasm.go:21:29
```

**Comment by Stebalien** [comment]
Are your deps up to date (and it looks like you're vendoring). `GOARCH=ppc64le go build` works fine on my machine.

**Comment by OTLabs** [comment]
You are so right! Updating the deps (just one of them) solved the issue. Thank you!
