### ISSUE TITLE
BLS signature validation across forks

### ISSUE THREAD

**Issue by whyrusleeping** [whyrusleeping/gx#236]
If I create a new BLS account, and then spend money from it immediately, miners that havent accepted the chain containing my account creation might not be able to validate the signature on my spend message, because validating a BLS signature requires looking up a public key from the chain (and that public key might not be there yet).

This may or may not be a problem, but its worth considering in our message validation logic.

One option could be to optionally include the public keys in the network message for BLS when it gets sent across the network. Otherwise, we could just say "wait a bit before spending from your BLS accounts".

needs more thought.

**Comment by dignifiedquire** [comment]
this is not the repo you are looking for

**Comment by whyrusleeping** [comment]
ah dammit.
