### ISSUE TITLE
Breaking change in dependency

### ISSUE THREAD

**Issue by bailer** [whyrusleeping/gx#240]
Hello, when installing `gx` it fails due to breaking API changes in the 2.x versions of `urfave/cli` so the building and installation of this package fails. I'm quite new to go but I assume it's because of the lack of dependency version pinning. I solved it by initializing go modules in the source folder so it used the proper package of `urfave/cli` instead of the master branch.

I can't purpose a permanent solution since I'm not involved enough in this project and new to go development, I just stumbled upon this issue when trying to install `ipfs/iptb` and `ipfs/iptb-plugins`.

**Comment by Stebalien** [comment]
Please use go modules to build IPTB and the plugins.

(however, I am going to switch this package over to go mod to ensure this doesn't keep happening)
