### ISSUE TITLE
Killing gx while it is installing deps leaves source directories in bad state

### ISSUE THREAD

**Issue by Kubuxu** [whyrusleeping/gx#29]
In my case the rewrite was not run so it wasn't working.

There should be lock file or something similar to signal that source directory was processed properly

**Comment by lgierth** [comment]
OpenWrt uses stamp-files, e.g. `.stamp.installed`, `.stamp.built`, etc.

**Comment by whyrusleeping** [comment]
working on this here: https://github.com/whyrusleeping/gx/tree/hook-run-files

**Comment by whyrusleeping** [comment]
this has been addressed
