### ISSUE TITLE
How to set up a development environment?

### ISSUE THREAD

**Issue by adamnovak** [whyrusleeping/gx#32]
When I clone the repo and run `go build`, I get:

```
main.go:13:2: cannot find package "github.com/blang/semver" in any of:
	/usr/local/go/src/github.com/blang/semver (from $GOROOT)
	/Users/anovak/Documents/Workspace/Go/src/github.com/blang/semver (from $GOPATH)
main.go:14:2: cannot find package "github.com/codegangsta/cli" in any of:
	/usr/local/go/src/github.com/codegangsta/cli (from $GOROOT)
	/Users/anovak/Documents/Workspace/Go/src/github.com/codegangsta/cli (from $GOPATH)
main.go:15:2: cannot find package "github.com/whyrusleeping/gx/gxutil" in any of:
	/usr/local/go/src/github.com/whyrusleeping/gx/gxutil (from $GOROOT)
	/Users/anovak/Documents/Workspace/Go/src/github.com/whyrusleeping/gx/gxutil (from $GOPATH)
main.go:16:2: cannot find package "github.com/whyrusleeping/stump" in any of:
	/usr/local/go/src/github.com/whyrusleeping/stump (from $GOROOT)
	/Users/anovak/Documents/Workspace/Go/src/github.com/whyrusleeping/stump (from $GOPATH)
```

It looks like, according to the Internet, the solution is to run `go get ./...`, but then I'm stuck using the Github version of gxutil, so if I were to want to make a change in that package, I'm not sure how I'd do that.

It also looks like my checkout has to be under `$GOPATH/src`.

This is all probably obvious information for anyone who has ever used Go before, but I haven't, so I would appreciate a simple step-by-step guide in the README for getting set up. Something like:

```
cd $GOPATH/src
git clone git@github.com:whyrusleeping/gx.git
cd gx
go get ./...
go build
```

Is that actually the right procedure to get set up? How should I extend it if I also want to tinker with a dependency?

If this is the Right Way, I'll open a PR.

**Comment by Kubuxu** [comment]
I usually do:
```
go get -d github.com/whyrusleeping/gx
cd $GOPATH/src/github.com/whyrusleeping/gx
go build
```
It works afaik.

**Comment by whyrusleeping** [comment]
what @Kubuxu says here is the recommended way of setting up a gx dev environment, I'll add it to the readme

**Comment by whyrusleeping** [comment]
docs updated in the readme
