### ISSUE TITLE
Command for returning hashe for pins required to secure dependencies

### ISSUE THREAD

**Issue by Kubuxu** [whyrusleeping/gx#35]
or a command that would create one object with all dependencies in flat hierarchy (as in `gx` directory after installing all dependencies).

Would be useful in cases that we don't want to accidentally loose some dependency.

**Comment by whyrusleeping** [comment]
`gx deps bundle`

**Comment by Kubuxu** [comment]
Oh, sorry, I wasn't aware of that.

**Comment by whyrusleeping** [comment]
no worries, just goes to show i need to write better docs
