### ISSUE TITLE
Issues installing

### ISSUE THREAD

**Issue by RichardLitt** [whyrusleeping/gx#36]
```
🐕   go get -d github.com/ipfs/go-ipfs
11:49 ~/src/http-api-spec (feature/name) * 🐕  cd $GOPATH/src/github.com/ipfs/go-ipfs
11:49 ~/gocode/src/github.com/ipfs/go-ipfs (master) 🐕  make install
go get -u github.com/whyrusleeping/gx
go get -u github.com/whyrusleeping/gx-go
gx --verbose install --global
make: gx: No such file or directory
make: *** [deps] Error 1
```

**Comment by noffle** [comment]
Go stores its binaries in `$GOPATH/bin`, so you'll need to add that to your `$PATH`, which controls where your system looks for commands that you can run:

```
export PATH=$PATH:$GOPATH/bin
```

You can run this per-session or put it in your `.bashrc` file.

**Comment by RichardLitt** [comment]
This appears to fix the issue. Thanks.

**Comment by whyrusleeping** [comment]
I should probably add a check to the ipfs makefile to ensure that the user has a gopath set properly
