### ISSUE TITLE
IPFS_API var needs to be manually set on windows

### ISSUE THREAD

**Issue by slothbag** [whyrusleeping/gx#38]
Without this environment variable set gx will not publish or import.  It appears it is not set automatically anywhere.

**Comment by whyrusleeping** [comment]
`IPFS_API` is an override variable, the value normally comes from `$IPFS_PATH/api`, but the `$HOME` env var doesnt exist on windows, so the fallback isnt working, this should be addressed in #40

**Comment by whyrusleeping** [comment]
should be fixed now, confirm and close @slothbag ?

**Comment by slothbag** [comment]
Yup, seems to be working. Closing. Thanks
