### ISSUE TITLE
files considered harmful

### ISSUE THREAD

**Issue by jbenet** [whyrusleeping/gx#4]
```js
  "Files": [
    "LICENSE",
    "README.md",
    "codec.go",
    "doc.go",
    "interface.go",
    "multiaddr.go",
    "multiaddr_test.go",
    "package.json",
    "protocols.csv",
    "protocols.go",
    "util.go"
  ],
```

is a bad idea because it strongly encourages the developer to have a _different_ dev environment than the consumers of the package, which invariably leads to lack of parity, testing, and correctness.

The approach npm takes is the opposite. it adds _everything_, _except_ things in `.gitignore` OR `.npmignore`. I think a `.gxignore` similarly makes sense.

**Comment by jbenet** [comment]
```
> gx add ./*
> cat package.json
{
  "Name": "go-multihash",
  "Files": [
    "LICENSE",
    "Makefile",
    "README.md",
    "gen",
    "io.go",
    "io_test.go",
    "multihash",
    "multihash.go",
    "multihash_test.go",
    "opts",
    "package.json",
    "sum.go",
    "sum_test.go",
    "test"
  ],
  "Version": "",
  "Dependencies": null,
  "Bin": "",
  "Build": "",
  "Test": "",
  "Language": ""
}
```

### Hmmm not what i expected

missing some files...

> gx add ./**/*
> cat package.json
{
  "Name": "go-multihash",
  "Files": [
    "LICENSE",
    "Makefile",
    "README.md",
    "gen",
    "io.go",
    "io_test.go",
    "multihash",
    "multihash.go",
    "multihash/LICENSE",
    "multihash/README.md",
    "multihash/install.dist.sh",
    "multihash/main.go",
    "multihash/multihash",
    "multihash_test.go",
    "opts",
    "opts/README.md",
    "opts/coding.go",
    "opts/opts.go",
    "package.json",
    "sum.go",
    "sum_test.go",
    "test",
    "test/Makefile",
    "test/bin",
    "test/bin/multihash",
    "test/sharness",
    "test/sharness/Makefile",
    "test/sharness/bin",
    "test/sharness/lib",
    "test/sharness/lib/install-sharness.sh",
    "test/sharness/lib/sharness",
    "test/sharness/lib/sharness/API.md",
    "test/sharness/lib/sharness/CHANGELOG.md",
    "test/sharness/lib/sharness/COPYING",
    "test/sharness/lib/sharness/Makefile",
    "test/sharness/lib/sharness/README.git",
    "test/sharness/lib/sharness/README.md",
    "test/sharness/lib/sharness/aggregate-results.sh",
    "test/sharness/lib/sharness/sharness.sh",
    "test/sharness/lib/sharness/test",
    "test/sharness/lib/sharness/test/Makefile",
    "test/sharness/lib/sharness/test/aggregate-results.sh",
    "test/sharness/lib/sharness/test/sharness.sh",
    "test/sharness/lib/sharness/test/sharness.t",
    "test/sharness/lib/sharness/test/simple.t",
    "test/sharness/lib/test-aggregate-results.sh",
    "test/sharness/lib/test-lib.sh",
    "test/sharness/t0010-basics.sh",
    "test/sharness/t0020-sha1.sh",
    "test/sharness/test-results",
    "test/sharness/test-results/t0010-basics.sh.95696.counts",
    "test/sharness/test-results/t0020-sha1.sh.95742.counts"
  ],
  "Version": "",
  "Dependencies": null,
  "Bin": "",
  "Build": "",
  "Test": "",
  "Language": ""
}

### ok not what i wanted either

definitely want .gitignore respected...

**Comment by whyrusleeping** [comment]
okay, I'll switch it over to add everything but use a `.gxignore` file and also have it respect the gitignore
