### ISSUE TITLE
Tags or version info

### ISSUE THREAD

**Issue by Kubuxu** [whyrusleeping/gx#44]
As I packaged gx and gx-go onto AUR automated way of getting version info from source files would be great.

I could sed my way through the source file but dedicated file with version info or git tags would be much better.

**Comment by whyrusleeping** [comment]
I added a version bump and tag, `v0.4.0` here. Will do similar for `gx-go`

**Comment by whyrusleeping** [comment]
I pushed a `v0.3.0` tag for `gx-go`

**Comment by Kubuxu** [comment]
Thanks I will update the AUR packages to use tags.
