### ISSUE TITLE
latest gx cant restore packages for IPFS on windows

### ISSUE THREAD

**Issue by slothbag** [whyrusleeping/gx#45]
i just built latest gx and gx-go and cant fetch all the deps to build ipfs.  It seems to lock up installing go-net package.

**Comment by whyrusleeping** [comment]
do you have a daemon running? If so, try turning your local daemon off and re-running the install.

Also try deleting your currently installed gx packages (`rm -rf $GOPATH/src/gx/`)

some of the packages will take a bit of time to perform the post-update step (like go-net, go-text, and gogo-protobuf), on slower machines that might seem like a hang (i'm trying to find a good way to show a progress bar on this)

**Comment by slothbag** [comment]
gx fallback to public gateway does not work on windows.  I can only do it via local daemon.

Currently I am doing a gx i, then after 5 minutes hitting ctrl-c and then rm vendor -rf then gx i again, after 10 iterations of this I am nearly all the way through :)

**Comment by slothbag** [comment]
I'm not able to build IPFS on windows right now due to gx error:

ERROR: building rewrite mapping failed:  loading dep "go-text" of "go-net": failed to find package: open

**Comment by whyrusleeping** [comment]
are you building using `make install` in the ipfs directory? Both running that, and `gx --verbose install --global` work on the windows VM i just spun up. This is without a daemon running locally.

**Comment by slothbag** [comment]
I didn't realize it had to be --global.. tried it again and it works. My bad.
