### ISSUE TITLE
Pass --global flag to postinstall hook

### ISSUE THREAD

**Issue by sterpe** [whyrusleeping/gx#60]
I am working on gx-js.  In node as part of the post install hook the gx-js hook will need to link the bin file to either  $pwd/node_modules/.bin in the local install folder or from NODE_PATH/../../lib/node_modules to NODE_PATH/../bin for a global install.  It's problematic to assume that it was a global install based on only on the shape of the path to the newly installed module provided as the current arg to the hook.  Since we need to do slightly different things it would be helpful to have that flag as an arg to post install too.

**Comment by whyrusleeping** [comment]
done! (good suggestion)
