### ISSUE TITLE
need a homebrew package

### ISSUE THREAD

**Issue by whyrusleeping** [whyrusleeping/gx#64]
This was requested in irc

**Comment by thomasjo** [comment]
This was added in https://github.com/Homebrew/homebrew-core/pull/193 (specifically [this commit](https://github.com/Homebrew/homebrew-core/commit/45ee208058f06d960120dbe0e2be78004b80b888)).

**Comment by jedahan** [comment]
you can close this issue, though any feedback on how to make said package better is totally welcome!

**Comment by whyrusleeping** [comment]
I'll go ahead and close this now, but if there is any feedback on that package, don't hesitate to let us know.
