### ISSUE TITLE
No new line character at the end of package.json

### ISSUE THREAD

**Issue by chriscool** [whyrusleeping/gx#71]
When importing a package, gx rewrites the package.json and doesn't add a new line character after the last '}' which is annoying as it often gives the following kind of diff:

```
@@ -71,4 +77,4 @@
   "license": "MIT",
   "name": "go-ipfs",
   "version": "0.4.0"
-}
+}
\ No newline at end of file
```

It would be nice if gx would just add a new line character after the last '}'.

**Comment by whyrusleeping** [comment]
Taken care of :) Thanks!
