### ISSUE TITLE
gx publish on windows to remote ipfs node fails

### ISSUE THREAD

**Issue by slothbag** [whyrusleeping/gx#73]
Error is `ERROR: publishing: object/patch/add-link: invalid ipfs ref path`

Both running latest master ipfs and gx

Publish using a local ipfs node works fine

**Comment by whyrusleeping** [comment]
@slothbag thanks for reporting, i'll take a look into this. Its very likely to be pathing differences (again)

**Comment by slothbag** [comment]
No worries, when I get a break in the coming days I'll try dig a little deeper.  But yeah, seems like path slashes again.

**Comment by slothbag** [comment]
Updated gx and deps and problem seems to have gone away.

**Comment by whyrusleeping** [comment]
@slothbag great to hear!
