### ISSUE TITLE
command to pin all deps

### ISSUE THREAD

**Issue by slothbag** [whyrusleeping/gx#85]
It would be great if there was an option to pin all deps to a IPFS node.

I often find myself starting a new IPFS install and have to manually re-pin all my gx packages into the new instance.

**Comment by whyrusleeping** [comment]
@slothbag for a given package you can do `gx deps bundle` to generate a single ipfs hash that references all dependencies of a given package.

**Comment by slothbag** [comment]
Perfect, thanks.
