### ISSUE TITLE
Will moving a repo across orgs break gx?

### ISSUE THREAD

**Issue by RichardLitt** [whyrusleeping/gx#86]
If we move go-multiaddr from the jbenet user account to multiformats, will this break anything? How do we prepare for this, test it, or avoid it entirely?

**Comment by whyrusleeping** [comment]
It shouldnt be a big deal, the problems that would arise would be if we updated the import paths in go-ipfs to point to the new address. In that case we would have to update the dvcs-import field in the package.json. Nothing will break without us explicitly breaking it in the code.

**Comment by RichardLitt** [comment]
Cool. Should we just keep this open until they are moved, and see if it happens, or can we take defensive procedures to make sure dvcs-import field works?

**Comment by whyrusleeping** [comment]
Yeah, the dvcs-import field will need to be changed at the same time that a package importing it changes their import.

Example:

In package A:
```
package A

import (
    "B"
)

```

Lets say package A imports B at QmBBB.
Then package "B" is being moved from "B" to "C".  Nothing will change as far as A is concerned, the imported gx package is still the same, and A still imports "B" as "B". Now, in "C" (ex-B) we update the dvcs-import to "C" and publish QmCCC. When A wants to update their version of B to C, they will have to remove the "B" dependency, Change their import from "B" to "C", and then import "C" as a new package.

**Comment by RichardLitt** [comment]
So it will break all dependencies, but only when they want to import?

**Comment by whyrusleeping** [comment]
It will only break if they try to update. until and unless they do, nothing changes

**Comment by RichardLitt** [comment]
Ok. Thanks; this is good to know.
