### ISSUE TITLE
golang: ability to import other people's packages

### ISSUE THREAD

**Issue by jbenet** [whyrusleeping/gx#9]
other packages often dont have gx package.jsons. it's annoying to have to go in there and define one. maybe should be able to have a way to import any package, and the version gets set to the full hash in that case.

**Comment by whyrusleeping** [comment]
working on a tool for this now.

**Comment by whyrusleeping** [comment]
@jbenet take a look at https://github.com/whyrusleeping/gx-go-import

I'm working on making it really easy to start importing packages into gx.

example usage:
```
whyrusleeping@idril ~/g/s/g/w/gx-go-import (master)> ./gx-go-import github.com/whyrusleeping/hellabot
vendoring package github.com/whyrusleeping/hellabot
processing dep github.com/mudler/sendfd for github.com/whyrusleeping/hellabot [1 / 1]
published github.com/mudler/sendfd as QmZk3DcHKZPbcaJ8ByMU3j9TepBGogo3T5dTH2ZAiUKoEo
published github.com/whyrusleeping/hellabot as QmPZ6gM12JxshKzwSyrhbEmyrsi7UaMrnoQZL6mdrzSfh1
```

**Comment by jbenet** [comment]
that sh ouput LGTM!
